### ISSUE TITLE
mina模拟https请求

### ISSUE THREAD

**Issue by 18792570983** [wucao/mina-netty-twisted#2]
javax.net.ssl.SSLHandshakeException: SSL handshake failed.
Caused by: javax.net.ssl.SSLException: Received fatal alert: certificate_unknown
请问这两个异常有什么办法解决

**Comment by wucao** [comment]
证书错误。先检查证书是不是正规CA机构颁发的，如果不是（比如自签名证书），需要把证书加入信任，具体可以网上找到方法。
